"""add github_app_installations

Revision ID: 34e197305dbd
Revises: 003_teams_github
Create Date: 2026-01-25 22:12:47.699109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34e197305dbd'
down_revision: Union[str, None] = '003_teams_github'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_github_actions_project_id', table_name='github_actions')
    op.drop_index('ix_github_actions_status', table_name='github_actions')
    op.alter_column('github_insights', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_insights', 'views_uniques',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_insights', 'clones_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_insights', 'clones_uniques',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_insights', 'stars_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_insights', 'forks_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_insights', 'watchers_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_insights', 'open_issues_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_issues', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('github_issues', 'comments_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_github_issues_project_id', table_name='github_issues')
    op.drop_index('ix_github_issues_state', table_name='github_issues')
    op.alter_column('github_projects', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('github_projects', 'items_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_github_projects_project_id', table_name='github_projects')
    op.drop_index('ix_github_wiki_project_id', table_name='github_wiki_pages')
    op.alter_column('messages', 'processing_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_project_issues_project_id', table_name='project_issues')
    op.drop_index('ix_project_issues_status', table_name='project_issues')
    op.drop_index('ix_projects_team_id', table_name='projects')
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('owner', 'admin', 'member', 'viewer', name='teamrole'),
               nullable=False)
    op.alter_column('team_members', 'status',
               existing_type=postgresql.ENUM('pending', 'active', 'inactive', 'declined', name='teammemberstatus'),
               nullable=False)
    op.drop_index('ix_team_members_team_id', table_name='team_members')
    op.drop_index('ix_team_members_user_id', table_name='team_members')
    op.drop_constraint('uq_team_github_member', 'team_members', type_='unique')
    op.alter_column('teams', 'is_personal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_teams_owner_id', table_name='teams')
    op.drop_index('ix_teams_slug', table_name='teams')
    op.alter_column('users', 'github_access_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'github_access_token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_index('ix_teams_slug', 'teams', ['slug'], unique=False)
    op.create_index('ix_teams_owner_id', 'teams', ['owner_id'], unique=False)
    op.alter_column('teams', 'is_personal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint('uq_team_github_member', 'team_members', ['team_id', 'github_username'])
    op.create_index('ix_team_members_user_id', 'team_members', ['user_id'], unique=False)
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.alter_column('team_members', 'status',
               existing_type=postgresql.ENUM('pending', 'active', 'inactive', 'declined', name='teammemberstatus'),
               nullable=True)
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('owner', 'admin', 'member', 'viewer', name='teamrole'),
               nullable=True)
    op.create_index('ix_projects_team_id', 'projects', ['team_id'], unique=False)
    op.create_index('ix_project_issues_status', 'project_issues', ['status'], unique=False)
    op.create_index('ix_project_issues_project_id', 'project_issues', ['project_id'], unique=False)
    op.alter_column('messages', 'processing_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_github_wiki_project_id', 'github_wiki_pages', ['project_id'], unique=False)
    op.create_index('ix_github_projects_project_id', 'github_projects', ['project_id'], unique=False)
    op.alter_column('github_projects', 'items_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_projects', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index('ix_github_issues_state', 'github_issues', ['state'], unique=False)
    op.create_index('ix_github_issues_project_id', 'github_issues', ['project_id'], unique=False)
    op.alter_column('github_issues', 'comments_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_issues', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('github_insights', 'open_issues_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_insights', 'watchers_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_insights', 'forks_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_insights', 'stars_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_insights', 'clones_uniques',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_insights', 'clones_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_insights', 'views_uniques',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_insights', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_github_actions_status', 'github_actions', ['status'], unique=False)
    op.create_index('ix_github_actions_project_id', 'github_actions', ['project_id'], unique=False)
    # ### end Alembic commands ###
