"""
Pydantic schemas for UI Designer API.

Defines request and response models for UI design generation endpoints.
"""

from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any

from pydantic import BaseModel, Field


class DesignStatus(str, Enum):
    """Status of a UI design generation."""
    PENDING = "pending"
    DETECTING = "detecting"
    OPTIMIZING = "optimizing"
    GENERATING = "generating"
    STREAMING = "streaming"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class FileType(str, Enum):
    """Type of generated file."""
    COMPONENT = "component"
    PAGE = "page"
    LAYOUT = "layout"
    STYLE = "style"
    CONFIG = "config"
    UTIL = "util"
    HOOK = "hook"
    TYPE = "type"
    TEST = "test"


class GeneratedFile(BaseModel):
    """A file generated by the UI Designer."""
    path: str = Field(..., description="Full file path relative to project root")
    content: str = Field(..., description="Complete file content")
    file_type: FileType = Field(default=FileType.COMPONENT, description="Type of the file")
    language: str = Field(default="typescript", description="Programming language (tsx, vue, blade, css)")
    lines_of_code: int = Field(default=0, description="Number of lines in the file")
    dependencies: List[str] = Field(default_factory=list, description="Required imports/packages")
    preview_url: Optional[str] = Field(default=None, description="URL for live preview if available")

    class Config:
        from_attributes = True


class UIDesignRequest(BaseModel):
    """Request body for UI design generation."""
    request: str = Field(..., description="User's design request", min_length=3, max_length=5000)
    conversation_id: Optional[str] = Field(default=None, description="Conversation ID for context")
    stream: bool = Field(default=True, description="Enable SSE streaming for real-time updates")
    include_preview: bool = Field(default=False, description="Generate preview URLs for files")

    class Config:
        json_schema_extra = {
            "example": {
                "request": "Create a dashboard with user stats cards, a recent activity table, and a line chart showing weekly trends",
                "stream": True,
                "include_preview": False,
            }
        }


class TechStackInfo(BaseModel):
    """Information about detected technology stack."""
    primary_framework: str = Field(..., description="Primary frontend framework (react, vue, blade, livewire)")
    css_framework: str = Field(..., description="CSS framework (tailwind, bootstrap, vanilla)")
    ui_libraries: List[str] = Field(default_factory=list, description="UI component libraries")
    uses_typescript: bool = Field(default=False, description="Whether project uses TypeScript")
    uses_inertia: bool = Field(default=False, description="Whether project uses Inertia.js")
    component_path: str = Field(default="", description="Path to components directory")
    page_path: str = Field(default="", description="Path to pages directory")


class DesignSummary(BaseModel):
    """Summary of the design generation."""
    total_files: int = Field(default=0, description="Total number of files generated")
    total_lines: int = Field(default=0, description="Total lines of code generated")
    components_created: List[str] = Field(default_factory=list, description="Names of components created")
    styles_generated: List[str] = Field(default_factory=list, description="Style files generated")
    dependencies_added: List[str] = Field(default_factory=list, description="New dependencies that may need to be installed")


class UIDesignResult(BaseModel):
    """Result of a UI design generation."""
    success: bool = Field(..., description="Whether generation was successful")
    design_id: str = Field(..., description="Unique identifier for this design")
    status: DesignStatus = Field(..., description="Current status of the design")
    files: List[GeneratedFile] = Field(default_factory=list, description="Generated files")
    summary: DesignSummary = Field(default_factory=DesignSummary, description="Design summary")
    tech_stack: Optional[TechStackInfo] = Field(default=None, description="Detected technology stack")
    error: Optional[str] = Field(default=None, description="Error message if failed")
    tokens_used: int = Field(default=0, description="Total tokens used for generation")
    generation_time_ms: int = Field(default=0, description="Time taken for generation in milliseconds")

    class Config:
        from_attributes = True


class UIDesignResponse(BaseModel):
    """Response for UI design generation (non-streaming)."""
    success: bool
    design_id: str
    message: str
    result: Optional[UIDesignResult] = None

    class Config:
        json_schema_extra = {
            "example": {
                "success": True,
                "design_id": "design_abc123",
                "message": "UI design generated successfully",
                "result": {
                    "success": True,
                    "design_id": "design_abc123",
                    "status": "completed",
                    "files": [
                        {
                            "path": "resources/js/Components/Dashboard/StatsCard.tsx",
                            "content": "// Component code...",
                            "file_type": "component",
                            "language": "tsx",
                            "lines_of_code": 45,
                        }
                    ],
                    "summary": {
                        "total_files": 3,
                        "total_lines": 150,
                        "components_created": ["StatsCard", "ActivityTable", "TrendChart"],
                    },
                }
            }
        }


class DesignStatusResponse(BaseModel):
    """Response for design status check."""
    design_id: str
    status: DesignStatus
    progress: float = Field(default=0.0, ge=0.0, le=1.0, description="Progress from 0.0 to 1.0")
    current_phase: str = Field(default="", description="Current phase of generation")
    files_completed: int = Field(default=0, description="Number of files completed")
    total_files: int = Field(default=0, description="Total files to generate")
    error: Optional[str] = None


class TechDetectionResponse(BaseModel):
    """Response for technology detection endpoint."""
    success: bool
    tech_stack: TechStackInfo
    design_tokens_found: bool
    existing_components_count: int
    message: str


class CancelDesignRequest(BaseModel):
    """Request to cancel an ongoing design generation."""
    design_id: str = Field(..., description="ID of the design to cancel")


class CancelDesignResponse(BaseModel):
    """Response for design cancellation."""
    success: bool
    design_id: str
    message: str


class PreviewRequest(BaseModel):
    """Request for file preview."""
    file_path: str = Field(..., description="Path of the file to preview")
    content: str = Field(..., description="File content to preview")
    framework: str = Field(default="react", description="Frontend framework for preview")


class PreviewResponse(BaseModel):
    """Response for file preview."""
    success: bool
    preview_url: Optional[str] = None
    preview_html: Optional[str] = None
    error: Optional[str] = None


# ============== SSE Event Data Models ==============


class DesignStartedData(BaseModel):
    """Data for design_started event."""
    design_id: str
    request: str
    message: str
    agent: str = "palette"
    agent_name: str = "Palette"


class TechDetectedData(BaseModel):
    """Data for tech_detected event."""
    framework: str
    css_framework: str
    ui_libraries: List[str]
    uses_typescript: bool
    message: str


class CodeChunkData(BaseModel):
    """Data for code_chunk event."""
    file_path: str
    chunk: str
    chunk_index: int
    accumulated_length: int
    total_length: int
    progress: float
    done: bool
    content: Optional[str] = None  # Only when done=True


class ComponentCompletedData(BaseModel):
    """Data for component_completed event."""
    component_name: str
    component_index: int
    total_components: int
    file_path: str
    lines_of_code: int
    message: str


class DesignCompletedData(BaseModel):
    """Data for design_completed event."""
    design_id: str
    files_count: int
    components_count: int
    total_lines: int
    generation_time_ms: int
    message: str
    files: List[Dict[str, Any]]  # Simplified file info for event
